#!/bin/bash
### BEGIN INIT INFO
# Provides:          dionaealog
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start dionaealog at boot time
# Description:       Dionaea intention is to trap malware exploiting vulnerabilities exposed by services offerd to a network, the ultimate goal is gaining a copy of the malware.
### END INIT INFO

PIDFILE=/var/run/dionaealog.pid
DAEMON=dionaealog.py
DESC="Dionaealog"
ROOTDIR=/usr/share/ossim/scripts/
test -d $ROOTDIR || exit 0

case $1 in
start)
  echo -n "Starting $DESC: "
  if [ -e $PIDFILE ]; then
    echo "already running, please stop first"
    exit 1
  fi
  cd $ROOTDIR
  STATUS="OK"
  nohup python $DAEMON > /var/log/ossim/dionaea.out 2> /var/log/ossim/dionaea.err & > /dev/null || STATUS="FAILED"
  echo "$STATUS"
  ;;
stop)
  echo -n "Stopping $DESC: "
  if [ -e $PIDFILE ]; then
    neppid=`cat $PIDFILE`
    `kill -9 $neppid`;
    rm $PIDFILE
    echo "OK"
  else
    echo "failed: no pid found"
  fi
  ;;
restart)
  shift
  $0 stop ${@}
  sleep 1
  $0 start ${0}
  ;;
*)
  echo "Usage: $0 {start|stop|restart}" >&2
  exit 1
  ;;
esac
exit 0

